---
title: Sabbatical Diary 2018
author: Doc P
date: '2020-06-16'
slug: sabbatical-diary-2018
categories: []
tags: []
---

May 1 - Downloaded “ Bookdown ” and played with it a bit but was unable to get it to work. Maybe tomorrow.

May 2 - figured out how to get the “Minimal Example” to work.  Downloaded MacTeX.  Watched into video on Bookdiwn: https://www.youtube.com/watch?v=dVqVscgwSpw&t=71s . Starting from scratch demo begins c 26:30. Updated R to current version. Added markdown

May 7 - Began working through the “tutorials.blogspot.com” tutorials and downloaded the data sets to go with them (data are on the Summer 2018 flash).

May 8 continued to work through the tutorials.  Some good ideas but things change so rapidly that much of the code is no longer necessary in the newer versions of R.  Proctored Janina’s exam at noon. Found a video - https://www.youtube.com/watch?v=mmmQ_7V9IZI - on new packages in R Markdown ecosystem.  Began watching before going to proctor exam. Got 10 minutes in.

May 10 -  Began with - https://www.youtube.com/watch?v=mmmQ_7V9IZI - New packages in R Markdown ecosystem. (Too much content to take in one bite, I’ll need to do this in parts).  R Markdown was not working on my laptop today.  I posted a question to the RStudio Community BB, went to Wendy’s and , by the time I got back, had a response from one of the developers.  Gotta love open source software. Watched Roger Peng’s “Introduction to the dplyr package”

May 11 - Started Hadley Wickham’s “Data Science With R” series.

May 14 - HSHS retreat

May 15 - Hospital talk

May 16 - ggplot2. http://ggplot2.tidyverse.org/

May 17 - Spent the day summarizing the statistics data for the assessment report.

May 18 -  reviewed the assessment report and did some advising in the am.  Back to gig-lot in pm.  Also downloaded a copy of “Microprogramming with Python” on programming micro controllers. Tidyverse also. 11:47 into Wickham’s first video

May 21 - Began reading R for Data Science (http://r4ds.had.co.nz/index.html) Made it through chapter 3.7 before my head started spinning.

May 22 -  Boat launch day Erie

May 23 -  TSA Webinar at 10, then to R for Data Science - got through 5.5.0

May 24 - Spent the morning working on ggplot examples (Markdown document Code Clips R4DS). Reference for ggplot 2 commands: http://ggplot2.tidyverse.org/reference/index.html. Finished (more or less) chapter 5 of R4DS.

May 25 - Began with R4DS Chapter 6.  Got through 6 and 7 but 7 is pretty dense and will require a return or two or three … 8 went much faster and I really should begin saving scripts and the like 9 is just an introduction to the data wrangling section of the book 10 will also require a few returns to really understand. Got to 11.3 before going screen blind.

May 26 - off

May 27 - Began re-watching the Marin  graphing videos to incorporate them into stat.  Got through #7

May 28 - Picked up n the Marin videos, but got distracted looking for data sets that are available for download.  Found a nice repository on GitHub - https://vincentarelbundock.github.io/Rdatasets/datasets.html 

May 29 -  found several useful data sets in the archive and downloaded them yesterday.  I’ll keep looking as time permits, as I would like to revise most of the data in class to use somewhat larger real data sets.  Back to the Marin graphing videos today.  Finished a set of notes (in TextWrangler) on 2.8 and reviewed 2.9.  I probably need to do a similar set on 2.9 and develop a markdown document for both.

May 30 -  Worked on Markdown documents for scatterplots and Boxplots.  

May 31 - added some material to the Boxplot handout and worked one up on subsetting. I decided in the afternoon to have another shot at r4ds chapter 10. Made it back to 11.3 but understood more this time.

June 1 -  Today’s plan is to review data frames in Yarrr and see if that helps to make sense of Tibbles in ggplot/R4DS - also going to work some on ggplot and try to make a final decision as to whether to try and incorporate it into stat.  

June 4 - Began to revise my crib sheets into Markdown format.  So far I have done the “Downloading/Installing R and RStudio” and “Data Entry” instructions.

June 5 -  Found a new Marin video this morning on using tapply to subset data, so I wrote a Markdown document first thing to summarize the steps. Started playing around some with R Notebooks.

June 6 - Decided to focus on Bookdown and R Notebooks for a while to see what use I might make of either or both.  Bookdown is a good way to combine individual Markdown files into a single, extended, document and Notebooks is said to be a good way to “communicate with other researchers” - it may be a better way to present material for class than simple Markdown documents.

June 7 - Time to index the markdown documents so I know what is on each one.

June 8 -  Got the index done yesterday including updating and cross referencing many of the files. Today I’ll keep going on the remaining inferential tests - MWU, Wilcoxon, ANOVA, KW.  Then the inferential part of statistics will be done.

June 11 - Hospital talk today on data visualization, so I worked up a Markdown handout (R, RStudio, and Data Vis) for the Docs.  It covers (briefly) Scatterplots, Boxplots, Barplots, Pie Charts, and Histograms.

June 12 - Spent the morning rewriting the Correlation crib sheet into Markdown. Afternoon was Simple Linear Regression.  The markdown crib sheets are much better if I do say so myself.

June 13 - Reviewed Week 3 and 4 homework - fine as is,

June 14 -  Spent most of the morning doing advising and the like.  Hope to work an ANOVA with R in the afternoon.

June 15 -  Off to a slow start because new software needed to be installed.  Repeated measures ANOVA in R today.

June 18 - Saturday was orientation Saturday so it was pretty much a lost cause.  The new orientation system does not impress me.  On Sunday I found a new Bayesian Statistics Coursera course (using R) so I’m going to try that this week,

June 19 -  Battling my way through Bayes.  Calculus was 50 years ago and is beyond rusty.

June 20 - Still doing Bayes and alternating with Marin lectures. STANDARD DEVIATION: https://www.youtube.com/watch?v=nlm9gfso4mw.   MARIN’S Website: http://www.statslectures.com/

June 21 - Happy first day of Summer. Still working on Bayes with R - I really need to go back and refresh some math if I’m going to understand this stuff, but I think I’ll work through all the videos and get an idea as to where I am going.  Then I can make a decision about whether the math review is worth while..

June 22 - New Marin lecture on Population vs Sample Started a new file on Marin videos 2018.  Back at the Bayes course and worked a bit on the use of various functions for distributions qnorm, pnorm, dnorm, rnorm, and the like

June 23 - July 1 -  Vacation on the Cape.

July 2 - Easing back in and catching up n all the tings that came in last week.  Reviewed a bunch of videos for inclusion in statistics

July 3 -  Eye exam and unable to read afterwards.  Watched a few videos where the narration was useful even without being able to focus on the visuals.

July 4 - Holiday.

July 5 Working on a quick review of calculus.

July 6 - Reading background material for Monday’s research meeting with Laurie Bladen. That took until about 1:30 Then read an article on the invisible gorilla: https://aeon.co/essays/are-humans-really-blind-to-the-gorilla-on-the-basketball-court

July 9 -  10 am Zoom with Laurie Bladen and then a hospital talk on research design and risk ratios.  Good talk with the docs, next month people want to talk about Mediteranian diet article remind and Nash equilibrium.

July 10 - Started out watching a Sara Locatelli video on mixed effect meta -analysis using R (which is way over my head), but went on to try and learn a bit more about meta analysis.  Also reviewed some of the resources from Laurie Bladen for the nursing workforce analysis project. - this looks doable.  Also watched the new Marin video on Confidence Interval for the Mean - https://www.youtube.com/watch?v=nKQ2KcCCnb0 - I will be using Marin’s videos (new and old) for class this fall). Just before leaving I found a new Marin video on exporting data from R to various non-data formats.  Always wanted to know how to do that (https://www.youtube.com/watch?v=WjpcbmcJjjM). 

July 11 - Reviewed Sonya Eckert’s schedule and transferred material from last fall’s courses into this fall’s shells. As this is Week 11 of the summer, and I have worked all but one week, I don’t feel any guilt about working on fall courses during my 10 week summer sabbatical.  The beginning of fall semester will be after 18 weeks of summer.

July 12 - Began working on revising statistics assignments and incorporating the new markdown documents in to the D2L site.

July 13 - Continued revising content in stat.

July 16, 17 -  Did the HIP list for Psychology and worked on D2L sites for Stat and General.  Simple line graphs in R using plot, type, and lines. Reviewed several of Marin’s graphing videos for class.

July 18 - Did a rather lengthy markdown handout on how to create a line graph in R with multiple groups and colors. It’s called Line graph in base R.

July 19 - Began watching videos on Mixed Effects ANOVA with R.  Marin doesn’t have one so I need to find a good alternate source.  Started with “Statistics of Doom” but it seems that too much background (from previous videos) is necessary.  I may come back if I can’t find something stand alone.
Christof Scherber’s Mixed effect models with R  seems better (Uses nlme package) - This one was better but still didn’t answer my question. Page Piccinini seems to have a nice series - I may watch the whole thing.

July 20 - Went to preview day at 9:50 Got a draft of the research proposal from Laurie Bladen

July 23 - Power out on campus, so the morning has so far, been a loss.  I’m going to write some notes for Laurie so I can send an email about the proposal when I again have power and internet.

July24 - Back to the Piccinini videos as well as a couple of new Marins

July 25 -  Bladen proposal first thing and then a meeting on Discovery Day 

July 26 - For some reason, my Air decided to encrypt all its files, so I had to fight with that first thing.  Then there were transfer evaluations to do.  Craig Scott at noon. Craig wanted pre professional curriculum maps from psychology - no problem.

July 27 - Spent the entire day doing Pre-professional Curriculum maps (18 of them).. Al=t least they are mostly done.

July 30 - back to Piccinini.  Hope to finish the series today. (Got through all but Lesson 6, Part 2 before lunch)
Finished the last video plus a couple of new Marin videos after lunch. Piccinini videos have a lot of good information in them, but are too advanced for my undergraduates.

July 31 - Converted all the pre-professional maps to Word and sent them off to Craig first thing this morning. Began reviewing the Marin videos on regression to see how far I can go in stat.

13 weeks done, minus 1 for vacation 12 weeks so far this year and 13 last year - 25 weeks down

August 1 - New Marin video: https://www.youtube.com/watch?v=AN3UkzE3HMg (Overview of statistics)

August 2 - Pinel Chapter 1 Downloaded all instructor resources

August 3 - Pinel Chapter 2

August 6 - 7 working on Pinel. Tuesday 2pm Screenflow webinar.

August 8 - Chapter 4 Pinel

August 9 - Biopsychology Syllabus

August 10 -  Online Psychology lab and preview day. (https://opl.apa.org/experiments/index.html?ERIGHTS=6zx2BVImCuMIThi33a8DkS3O7x2BjfRFTlGq-18x2d9s4NwxxaUV9EeA24DqhpckAx3Dx3D2XsFdaprr77QTTn1YW10hwx3Dx3D-2UDkZ0TjlQOtBoBHx2Fzq4bQx3Dx3D-ggx2FJp7FDx2BA1pRuszH2NgMAx3Dx3D#/Experiments)


