<!DOCTYPE html>
<html lang="en-us">

  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>R Chi Squared  | Slumdown</title>

  <link rel="stylesheet" href=../../css/palette_dark.css />
  
  <link rel="stylesheet" href="../../css/et_book.css" />
  <link rel="stylesheet" href="../../css/style.css" />

  
<meta name="twitter:card" content="summary">
<meta property="og:title" content="R Chi Squared ">
<meta property="og:description" content="Reference: Marin (R Tutorial 4.7) Chi Squared is a very useful test for evaluating categorical data. Perhaps the greatest difficulty students have with it is determining which version should be used in a particular situation and how to enter the data into R. We will do several examples, showing various ways to evluate information.
Single Classification Chi Squared We use the single classification test when we have only a single variable of interest (even though there may be several levels of that variable).">
<meta property="og:image" content="">

</head>


  <body>
    



    <div class="main-content">
      <nav>
  <ul class="menu">
    
    <li><a href="../../">Home</a></li>
    
    <li><a href="../../about/">About</a></li>
    
    <li><a href="../../post/">Posts</a></li>
    
    <li><a href="../../project/">Projects</a></li>
    
    <li><a href="../../tags/">Tags</a></li>
    
  </ul>
</nav>

      <div>
  <h1>R Chi Squared</h1>
  <h3>
    by Doc P, 09 Jun 2020
  </h3>
  <br><br>
</div>


      <main>
        


<p>Reference: Marin (R Tutorial 4.7)
Chi Squared is a very useful test for evaluating categorical data. Perhaps the greatest difficulty students have with it is determining which version should be used in a particular situation and how to enter the data into R. We will do several examples, showing various ways to evluate information.</p>
<div id="single-classification-chi-squared" class="section level3">
<h3>Single Classification Chi Squared</h3>
<p>We use the single classification test when we have only a single variable of interest (even though there may be several levels of that variable).</p>
<p>For our example I looked up the most recent data on the percentage of voters who are registered as Democrat (40%), Republican (29%), and Independent (28%). Note that the total only adds up to 97%, probably due to rounding.</p>
<p><strong>The Easiest Way</strong></p>
<p>Our first test will evaluate a null hypothesis (Ho) that all three categories are equally represented against the alternative (Ha) that at least one category differs from at least one other.</p>
<p>First, enter a vector of the registrations, and a second vector of the probabilities for each category under the null hypothesis (1/3 of the voters in each category).</p>
<pre class="r"><code>registrations &lt;- c(40, 29, 28)
null.probs &lt;- c(1/3, 1/3, 1/3)</code></pre>
<p>Then perform a Chi Squared test on these scores.</p>
<pre class="r"><code>chisq.test(registrations, p = null.probs)</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  registrations
## X-squared = 2.7423, df = 2, p-value = 0.2538</code></pre>
<p>The parameter “registrations” tells R what scores to evaluate and the parameter “p = null. probs” tells R what probability to assign to the expected outcome for each category.</p>
<p>Our obtained p value of 0.2538 is larger than our customary critical p value of 0.05, so we would retain the null hypothesis. Our data do not provide sufficient evidence for us to say that one party is preferred over another.</p>
<p>Because our probabilities are all equal and this is the default value for R, we could use an even simpler approach and get the same results.</p>
<pre class="r"><code>chisq.test(registrations)</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  registrations
## X-squared = 2.7423, df = 2, p-value = 0.2538</code></pre>
<p><strong>Slightly More Complicated</strong></p>
<p>We may not always want the expected outcomes to be equally distributed. If, for example, I wanted to compare the national data given above (40% D, 29% R, 28% I) with registrations in Clarion County, Pennsylvania (33% D, 59% R, 8% I) I would need to use these in the null probability vector.</p>
<pre class="r"><code>registrations &lt;- c(40, 29, 28)
null.probs2 &lt;- c(0.33, 0.59, 0.08)
chisq.test(registrations, p = null.probs2)</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  registrations
## X-squared = 68.71, df = 2, p-value = 1.202e-15</code></pre>
<p>There are a couple things of interest in these results. First, we are asking a different question. Our null hypothesis is now “Clarion county voter registrations are representative of the country as a whole” and our alternative is “Clarion county registrations are not representative of the country as a whole.” The second item of interest is that our p value is exceedingly small (p-value = 1.202e-15, means 0.000000000000001202, much less than 0.05). Therefore, we can reject the null hypothesis. Clarion county does not seem to be representative of national voter registration trends.</p>
<p>If you don’t like your p values presented in scientific notation, you can supress it.</p>
<pre class="r"><code>registrations &lt;- c(40, 29, 28)
null.probs2 &lt;- c(0.33, 0.59, 0.08)
options(scipen = 999)
chisq.test(registrations, p = null.probs2)</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  registrations
## X-squared = 68.71, df = 2, p-value = 0.000000000000001202</code></pre>
</div>
<div id="double-classification-chi-squared" class="section level3">
<h3>Double Classification Chi Squared</h3>
<p>The Double Classification Chi Squared is useful when you want to determine whether two variables are independent.</p>
<p>For our next Chi Squared example we will use the Lung Cap data set provided by Mike Marin. It can be downloaded from D2L if you have not already done so. Once you have the data, read the file in to R and attach it.</p>
<p>We will be looking at the relationship between Gender and Smoking.</p>
<p>We could print out the data set and count alll of the men and womne who either do or do not smoke, but that would be a tedious and error prone task. Instead, we will have R produce a table of these data.</p>
<pre class="r"><code>tab &lt;- table(Gender, Smoke)
tab</code></pre>
<pre><code>##         Smoke
## Gender    no yes
##   female 314  44
##   male   334  33</code></pre>
<p>It is also a good idea to create a bar plot of the data to get a visual image of the relationship.</p>
<pre class="r"><code>barplot(tab, beside = T, legend=T) </code></pre>
<p><img src="../../post/2020-06-09-r-chi-squared_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>“beside = T” tells R to put the bars beside each other and “legend = T” tells R to place a legend on the plot. This makes the plot easier to interpret.</p>
<p>To perform the actual analysis we use the “chisq.test” command.</p>
<pre class="r"><code>chisq.test(tab, correct = T)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  tab
## X-squared = 1.7443, df = 1, p-value = 0.1866</code></pre>
<p>“correct = T” tells R to apply Yates correction for continuity. This link - <a href="http://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity" class="uri">http://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity</a> - is to a page that explains the correction if you are unfamiliar with it. You may want to run the test both with and without the correction just to see if it makes any difference. The default in R is for the correction to be made so, if you do not want the correction you must specify a value of F for the parameter.</p>
</div>
<div id="a-second-approach-to-the-double-classification-chi-squared" class="section level3">
<h3>A Second Approach to the Double Classification Chi Squared</h3>
<p>Unfortunately we do not always have our data in a spreadsheet so we can get R to create a table for us. In this case we need to enter the data manually into a matrix and tell R how the matrix is constructed. We will use the same Smoke vs Gender data but assume that we just have the numbers for each of the four categories. (Female - Non-smoker 314, Female - Smoker 44, Male - Non-smoker 334, Male - Smoker 33)</p>
<p>First, we create the table. We will ue the “rbind command to tell R to enter the numbers by row. Row one will have 314 and 44 while row two will have 334 and 33.”dimnames&quot; simply attaches names to the rows and columns to make it easier to read the table.</p>
<pre class="r"><code>M &lt;- as.table(rbind(c(314, 44), c(334, 33)))
dimnames(M) &lt;- list(gender = c(&quot;F&quot;,&quot;M&quot;),
                    smoke = c(&quot;No&quot;, &quot;Yes&quot;))
M</code></pre>
<pre><code>##       smoke
## gender  No Yes
##      F 314  44
##      M 334  33</code></pre>
<p>It’s a good idea at this point to take a careful look at your table to see if it is set up the way you want (i.e., the numbers are in the right columns and rows and the names match what you intended to have happen).</p>
<p>Then we simply do the chisq.test on the values in the table.</p>
<pre class="r"><code>chisq.test(M)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  M
## X-squared = 1.7443, df = 1, p-value = 0.1866</code></pre>
<p>Note that, as we used the same numbers we had used in the previous example, our result is the same. That’s the way statistics works. Eitehr way, our p-value of 0.1866 tells us that we do not have enough evidence to claim that there is a relationship between gender and smoking.</p>
</div>

      </main>

      <footer>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>

  <script>
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  </script>

  <script src="//yihui.name/js/math-code.js"></script>
<script async src="//mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>

<script async src="//yihui.name/js/center-img.js"></script>

  
  <br/><br/>
  © Randy Potter 2020 | <a href="https://github.com/Sigmund7">Github</a>
  <br/><br/>
  
</footer>


    </div>
  </body>
</html>
